# Generated by Django 2.2.3 on 2020-02-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200213_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='liekes',
            new_name='likes',
        ),
    ]
